logging:
  level:
    root: debug
    net:
      reliqs:
        emonlight: debug
spring:
  datasource:
    url: jdbc:postgresql://lime2:5432/emonlight-db_dev
    username: emonlight
    password: emonlight
    driver-class-name: org.postgresql.Driver

spring.jpa.properties.javax.persistence.schema-generation.database.action: drop-and-create
spring.jpa.properties.javax.persistence.schema-generation.create-source: metadata
spring.jpa.properties.javax.persistence.schema-generation.scripts.action: create
spring.jpa.properties.javax.persistence.schema-generation.scripts.create-target: schema.sql
