logging:
  level:
    root: info
    net:
      reliqs:
        emonlight: trace
#    org.springframework.jdbc.core.JdbcTemplate: debug
    org.springframework.jdbc.core: debug
#spring:
#  datasource:
#    initialize: false
#  jms.isPubSubDomain: true
#  activemq:
#    broker-url: tcp://lime2:61616

spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
#    url: jdbc:mariadb://localhost:3306/emonlight_dev?createDatabaseIfNotExist=true&useSSL=false&assureReadOnly=true
    url: jdbc:mariadb://lime2:3306/emonlight?useSSL=false&assureReadOnly=true
    username: emonlight
    password: emonlight
    initialize: false
  jpa:
    show-sql: true
    generate-ddl: false
#    database-platform: org.hibernate.dialect.MySQLDialect
    properties:
      hibernate.dialect.storage_engine: myisam
      hibernate.dialect: org.hibernate.dialect.MySQLDialect
#      javax.persistence.schema-generation.create-source: metadata
#      javax.persistence.schema-generation.scripts.action: create
#      javax.persistence.schema-generation.scripts.create-target: schema.sql
    hibernate:
      ddl-auto: none

settings.path: src/test/resources/settings.yml
