logging:
  level:
    root: info
    net:
      reliqs:
        emonlight: trace

server:
  error.include-stacktrace: always
  servlet.context-path: /emonlight

spring:
  thymeleaf.cache: false
#  resources.cache-period: 0

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
#    url: jdbc:mariadb://localhost:3306/emonlight_dev?createDatabaseIfNotExist=true&useSSL=false&assureReadOnly=true
    url: jdbc:mariadb://xu4:3306/emonlight?useSSL=false&assureReadOnly=true&serverTimezone=UTC&sessionVariables=time_zone='+00:00'&useLegacyDatetimeCode=false
    username: emonlight
    password: emonlight
#    initialize: false
#  jpa:
#    show-sql: true
#    generate-ddl: false
##    database-platform: org.hibernate.dialect.MySQLDialect
#    properties:
#      hibernate.dialect.storage_engine: myisam
#      hibernate.dialect: org.hibernate.dialect.MySQLDialect
#      javax.persistence.schema-generation.create-source: metadata
#      javax.persistence.schema-generation.scripts.action: create
#      javax.persistence.schema-generation.scripts.create-target: schema.sql
#    hibernate:
#      ddl-auto: none

historyDays: 5

settings.path: out/settings.yml

#spring.jpa.properties.javax.persistence.schema-generation.database.action: drop-and-create
#spring.jpa.properties.javax.persistence.schema-generation.create-source: metadata
#spring.jpa.properties.javax.persistence.schema-generation.scripts.action: create
#spring.jpa.properties.javax.persistence.schema-generation.scripts.create-target: schema-postgresql.sql
