---
logging:
  level:
    root: INFO
    com.digi.xbee: INFO
    net:
      reliqs:
        emonlight: DEBUG     

#kafka:
#  bootstrap.servers: betulla:9092
#  zookeeperHosts: betulla:2181
#  noOfPartitions: 1
#  noOfReplication: 1

spring:
  activemq:
    broker-url: tcp://lime2:61616
  jms:
    pub-sub-domain: true

#    pool:
#      enabled: true