---
gatewayId: 1

settings:
  serialPort: "/dev/ttyUSB0"
  baudRate: 115200
  receiveTimeout: 2000
  nodes:
  - name: TEST
    address: 0013A20041468937
    sampleTime: 5000
    mode: PULSE_DHT22
    vccFromADC: true
    adcRange: 4095
    adcVRef: 3.3
    probes:
    - &TEST_PULSE
      name: TEST_PULSE
      type: PULSE
      softThreshold: 3300
      softThresholdTimeSec: 10800
      hardThreshold: 4000
      hardThresholdTimeSec: 240
    - &TEST_H
      name: TEST_H
      type: DHT22_H
      sampleTime: 40000
    - &TEST_T
      name: TEST_T
      type: DHT22_T
    - &TEST_VCC
      name: TEST_VCC
      type: VCC
      sampleTime: 60000
      adcMult: 3.42
  servers:
  - name: pino
    url: http://pino/emonlight-dev/input/read.json
    sendRate: 10000
    maps:
    - probe: *TEST_T
      nodeId: 8
      apiKey: nC1uDMkxnVJwKyKxQis5
    - probe: *TEST_H
      nodeId: 9
      apiKey: ywDxpCXDi2Pc4taeyYLN
    - probe: *TEST_VCC
      nodeId: 13
      apiKey: uKY33ArrQshrSeafDwqF
    - probe: *TEST_PULSE
      nodeId: 2
      apiKey: dcTRYGK7RB1kqxW2vE-Q
  - name: acero
    url: http://acero:3000/input/read.json
    sendRate: 10000
    maps:
    - probe: *TEST_PULSE
      nodeId: 2
      apiKey: dcTRYGK7RB1kqxW2vE-Q
